### ISSUE TITLE
Boton para subir pdf esta bloqueado

### ISSUE THREAD

**Issue by GenLoya** [pulgueta/PDFizado#2]
![imagen_2024-02-08_154400666](https://github.com/pulgueta/PDFizado/assets/134974289/8577a6ed-6d66-4582-a2dd-51675b239c0b)

**Comment by pulgueta** [comment]
Este issue ha sido resuelto en el último despliegue. Ya pueden subirse PDFs.

**Comment by pulgueta** [comment]
Issue solved in last commit as of today. (02/09/2024 4:35 a.m. EST)
